### ISSUE TITLE
Ordonner la liste publique : Fatal error avec PHP8 

### ISSUE THREAD

**Issue by Philippe-dev** [Philippe-dev/related#5]
Lorsqu'on ordonne la liste publique sous PHP 8 

`Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /var/www/dotclear.unstable.local/htdocs/dotclear/plugins/related/inc/panel.php:291 Stack trace: #0 /var/www/dotclear.unstable.local/htdocs/dotclear/plugins/related/inc/panel.php(291): explode() #1 /var/www/dotclear.unstable.local/htdocs/dotclear/plugins/related/index.php(20): include_once('...') #2 /var/www/dotclear.unstable.local/htdocs/dotclear/admin/plugin.php(43): include('...') #3 {main} thrown in /var/www/dotclear.unstable.local/htdocs/dotclear/plugins/related/inc/panel.php on line 291`

Par ailleurs, comme signalé sur le forum, sous php 7.4 pas d'erreur mais l'ordre des pages n'est pas conservé

**Comment by Philippe-dev** [comment]
Merci pour la correction mais ce n'est pas encore ça.  L'erreur sous PHP 8 a disparu, mais la modification d'ordre n'est pas conservée après l'enregistrement
